[tool.poetry]
name = "todolist"
version = "0.1.0"
description = ""
authors = ["Евгений Чайка <chay67ka26@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
